image: maven:3.3.9
pipelines:
  default:
    - step:
        name: Prepare and Execute Pipeline
        script:
          - mvn test
    - step:
        name: Submit Execution Results to qTest Pulse
        script:
          - cd "$WORKSPACE/target"
          - logs=$(<cucumber-report.json) #Read in file
          - echo ${logs}
          - curl -X POST "https://pulse-7.qtestnet.com/webhook/f23f9005-26e7-4862-8fe4-9840d7563b35" -H "Content-Type:application/x-www-form-urlencoded" -H "cache-control:no-cache"